export const NEWS_REQUEST = "NEWS_REQUEST";
export const NEWS_REQUEST_SUCCESS = "NEWS_REQUEST_SUCCESS";
export const NEWS_REQUEST_FAILED = "NEWS_REQUEST_FAILED";
export const NEWS_DETAIL_REQUEST = "NEWS_DETAIL_REQUEST";
export const NEWS_DETAIL_REQUEST_SUCCESS = "NEWS_DETAIL_REQUEST_SUCCESS";
export const NEWS_DETAIL_REQUEST_FAILED = "NEWS_DETAIL_REQUEST_FAILED";
